# -*- coding: utf-8 -*-
{
    'name': "Sale KSC",
    'summary': "The data of Sale",
    'description': """This models is all about understand the active attributes """,
    'author': "konsultoo",
    'website': "http://www.konsultoo.com",
    'category': 'Uncategorized',
    'version': '2.3',
    'depends': ['base','res_localization_ksc'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_category_ksc.xml',
        'wizard/product_stock_update_ksc_views.xml',
        'views/product_ksc.xml',
        'views/product_umo_ksc.xml',
        'views/product_umo_category_ksc.xml',
        'views/res_partner_ksc.xml',
        'views/sale_order_ksc.xml',
        'views/sale_order_line_ksc.xml',
        'views/crm_team_ksc.xml',
        'views/crm_lead_ksc.xml',
        'views/crm_lead_line_ksc.xml',
        'views/stock_warehouse_ksc.xml',
        'views/stock_location_ksc.xml',
        'views/stock_picking_ksc.xml',
        'views/stock_move_ksc.xml',
        'views/stock_inventory_ksc.xml',
        'views/stock_inventory_line_ksc.xml',
        'views/purchase_order_ksc.xml',
        'views/purchase_order_line_ksc.xml',
        'views/account_tax_ksc_view.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto-install': False,
    'license': 'LGPL-3',
}
