from . import product_category_ksc
from . import product_ksc
from . import product_umo_ksc
from . import product_umo_category_ksc
from . import res_partner_ksc
from . import sale_order_ksc
from . import sale_order_line_ksc
from . import crm_team_ksc
from . import crm_lead_ksc
from . import crm_lead_line_ksc
from . import stock_warehouse_ksc
from . import stock_location_ksc
from . import stock_picking_ksc
from . import stock_move_ksc
from . import stock_inventory_ksc
from . import stock_inventory_line_ksc
from . import purchase_order_ksc
from . import purchase_order_line_ksc
from . import account_tax_ksc